server:
  port: 9900
magic-api:
  #配置web页面入口
  web: /magic/web
  resource:
    type: database
    table-name: magic_api_file_v2

spring:
  datasource:
    url: jdbc:postgresql://192.168.31.124:5432/yunlios?currentSchema=form&useSSL=false&socketTimeout=30000
    username: yunlios
    password: yunlios@0120
    driver-class-name: org.postgresql.Driver


#mybatis:
#  mapper-locations: classpath:magic-server/src/main/resources/mapper/*.xml
#  type-aliases-package: org.xllyll.magicapi.demo.model

# MyBatis Plus 配置
mybatis-plus:
  # 搜索指定包别名
  type-aliases-package: org.**.model
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  #  config-location: classpath:mybatis/mybatis-config.xml
  # 日志打印配置
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl