magic-api:
  #配置web页面入口
  web: /magic/web
  resource:
    type: database
    table-name: magic_api_file_v2
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.31.124:5432/yunlios?currentSchema=form&useSSL=false&socketTimeout=30000
    username: yunlios
    password: yunlios@0120